version: '3.9'

services:
  web:
    build: .
    command: ./scripts/wait-for-it.sh mysql:3306 -- ./scripts/docker-entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mysql
    restart: on-failure
    volumes:
      - .:/app

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "${PORT}:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${NAME}
      MYSQL_ROOT_PASSWORD: ${PASSWORD}

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis_data:/data

  celery:
    build: .
    command: celery -A e_commerce worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app

  celery-beat:
    build: .
    command: celery -A e_commerce beat --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app

  flower:
    build: .
    command: celery -A e_commerce flower
    depends_on:
      - web
      - redis
      - celery
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://redis:${REDIS_PORT}/1
      - CELERY_BACKEND=redis://redis:${REDIS_PORT}/1
    ports:
      - "5555:5555"

volumes:
  data:
  redis_data: