version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_holding
    restart: always
    ports:
      - "${PORT}:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${NAME}
      MYSQL_ROOT_PASSWORD: ${PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_holding
    restart: always
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306